### ISSUE TITLE
[help] 我修改 SITE.website，打包就会报错

### ISSUE THREAD

**Issue by QuentinHsu** [liruifengv/liruifengv.com#24]
我可能需要一点点帮助，万分感谢！

https://github.com/liruifengv/liruifengv.com/blob/main/src/config.ts#L4

我将 `website: "https://liruifengv.com/"` 修改为我的地址，就会报错。

![image](https://github.com/liruifengv/liruifengv.com/assets/21162238/216af54f-c72e-4fb2-8b9e-4c89b3c23125)

我参照您的这个帖子 https://liruifengv.com/posts/astro-auto-gen-og-image/ 也未能排查到关键的问题。也尝试 Google 相关报错，无果。

目前猜测可能该地址需要具备某种条件？
- 能否访问到 `fonts/ZCOOL_KuaiLe/ZCOOLKuaiLe-Regular.ttf` 字体？

**Comment by liruifengv** [comment]
是的，问题就是你的网站下面没有对应字体文件。
可以先把生成og图片的逻辑注释，先把字体文件传上去。
然后再打包生成og

**Comment by QuentinHsu** [comment]
> 是的，问题就是你的网站下面没有对应字体文件。 可以先把生成og图片的逻辑注释，先把字体文件传上去。 然后再打包生成og

感谢！我据此顺利地解决了问题。
